/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemasubasta;

/**
 *
 * @author Aymer
 */

import java.net.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
public class InterfazOfertante extends javax.swing.JFrame {
    Socket socket;

    /**
     * Creates new form InterfazOfertante
     */
    public InterfazOfertante(String nick, String fecha, String precio, Socket socket) {

        initComponents();
        Nick.setText(nick);
        Fecha.setText("Termina el " + fecha);
        Precio.setText("Valor actual: " + precio);
        this.socket = socket;
    }

    public InterfazOfertante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Precio = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Ofertar = new javax.swing.JButton();
        Nick = new javax.swing.JLabel();
        Ofertadotextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Precio.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Precio.setText("Precio Actual = ");

        Fecha.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Fecha.setText("La subasta termina el .....");

        Ofertar.setText("Ofertar");
        Ofertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfertarActionPerformed(evt);
            }
        });

        Nick.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Nick.setText("Nick");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Ofertar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Ofertadotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Precio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Nick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Fecha)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Nick)
                .addGap(29, 29, 29)
                .addComponent(Fecha)
                .addGap(30, 30, 30)
                .addComponent(Precio)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ofertar)
                    .addComponent(Ofertadotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OfertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST
        try {
        DataOutputStream salida = new DataOutputStream(socket.getOutputStream());
        salida.writeInt(3);
        salida.writeUTF(Nick.getText());
        salida.writeUTF(Ofertadotextfield.getText());
    } catch (Exception e) {
        e.printStackTrace();}

    }//GEN-LAST:event_OfertarActionPerformed

    
    public void update() {
        System.out.println("Mensaje recibido: " );
        return;
    }
    
    public void unsubscribe() {
        return;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazOfertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazOfertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazOfertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazOfertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazOfertante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Nick;
    private javax.swing.JTextField Ofertadotextfield;
    private javax.swing.JButton Ofertar;
    public javax.swing.JLabel Precio;
    // End of variables declaration//GEN-END:variables
}
